apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

bases:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: prod

replicas:
  - name: demo-app
    count: 3

patchesStrategicMerge:
  - ingress-patch.yaml
  - resources-patch.yaml

configMapGenerator:
  - name: demo-app-html
    behavior: merge
    literals:
      - env=production
